---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: badstats
  namespace: badstats
spec:
  replicas: 2
  selector:
    matchLabels:
      app: badstats
  template:
    metadata:
      labels:
        app: badstats
    spec:
      # topologySpreadConstraints:
      # - maxSkew: 1
      #   topologyKey: kubernetes.io/hostname
      #   whenUnsatisfiable: ScheduleAnyway
      #   labelSelector:
      #     matchLabels:
      #       app: badstats
      containers:
        - name: badstats
          image: ghcr.io/kclapper/badstats:v1.2.1
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "300Mi"
              cpu: "500m"
            requests:
              memory: "50Mi"
              cpu: "200m"
          ports:
            - containerPort: 8080
          env:
            - name: REDIRECT_HOSTNAME
              value: "https://badstats.offtherailsradio.org"
            - name: CLIENTID
              valueFrom:
                secretKeyRef:
                  name: badstats
                  key: clientid
            - name: CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: badstats
                  key: clientsecret
            - name: FLASK_SECRET
              valueFrom:
                secretKeyRef:
                  name: badstats
                  key: flask_secret
            - name: FLASK_ENV
              value: "production"
          volumeMounts:
            - mountPath: /usr/src/app/instance
              name: data
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: db-pvc

---
kind: Service
apiVersion: v1
metadata:
  name: badstats
  namespace: badstats
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: badstats