---
# Redirect to https
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: badstats
spec:
  redirectScheme:
    scheme: https
    port: "443"
    permanent: true

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: badstats
  namespace: badstats
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: badstats-https-redirect@kubernetescrd
spec:
  tls:
  - hosts:
    - badstats.offtherailsradio.org
    secretName: badstats-tls
  rules:
  - host: badstats.offtherailsradio.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: badstats
            port:
              number: 8080