---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: badstats
spec:
  storageClassName: linode-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi